/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;
import java.lang.*;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import java.awt.print.Book.*;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;




public class recieved extends javax.swing.JInternalFrame {

    /**
     * Creates new form recieved
     */
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    private String parseSql;
    
    
    
    public recieved() {
         initComponents();
         conn=DBConnect.connect();
         autoId();
         tablelord();
         panelord();
         loDisable();
        
         
        
    }

    private void  theader()
    {
    JTableHeader thead = tableitemlist.getTableHeader();
       thead.setForeground(Color.BLUE);
    
       thead.setFont(new Font("Tahome", Font.BOLD, 14));
       
        TableColumn col1=tableitemlist.getColumnModel().getColumn(0);
        col1.setPreferredWidth(100);
        TableColumn col2=tableitemlist.getColumnModel().getColumn(1);
        col2.setPreferredWidth(110);
        TableColumn col3=tableitemlist.getColumnModel().getColumn(2);
        col3.setPreferredWidth(85);
        TableColumn col4=tableitemlist.getColumnModel().getColumn(3);
        col4.setPreferredWidth(100);
        TableColumn col5=tableitemlist.getColumnModel().getColumn(4);
        col5.setPreferredWidth(105);
        TableColumn col6=tableitemlist.getColumnModel().getColumn(5);
        col6.setPreferredWidth(95);
        TableColumn col7=tableitemlist.getColumnModel().getColumn(6);
        col7.setPreferredWidth(110);
        TableColumn col8=tableitemlist.getColumnModel().getColumn(7);
        col8.setPreferredWidth(115);
         TableColumn col9=tableitemlist.getColumnModel().getColumn(8);
        col9.setPreferredWidth(115);
         TableColumn col10=tableitemlist.getColumnModel().getColumn(9);
        col10.setPreferredWidth(110);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtreno = new javax.swing.JTextField();
        txtitemno = new javax.swing.JTextField();
        datereceive = new com.toedter.calendar.JDateChooser();
        dateexpire = new com.toedter.calendar.JDateChooser();
        txtitemname = new javax.swing.JTextField();
        txtdescription = new javax.swing.JTextField();
        txtquentity = new javax.swing.JTextField();
        txtbuyprice = new javax.swing.JTextField();
        txtsellprice = new javax.swing.JTextField();
        txttotalprice = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cmbsearch = new javax.swing.JComboBox<String>();
        btnsearch = new javax.swing.JButton();
        txtsearch = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnclear = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnselect = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnupdate = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnsave = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableitemlist = new javax.swing.JTable();
        lblbarcode = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(950, 530));

        jPanel1.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Item Details");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 30, 140, 26);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background4.jpg"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(30, 20, 290, 40);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Receving No");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 110, 100, 23);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Receving Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 140, 100, 23);

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Item No");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 180, 67, 23);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 210, 90, 23);

        jLabel5.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Description");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 240, 80, 23);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Quantity");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 310, 67, 23);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ex Date");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 270, 67, 23);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Buying Price");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 340, 90, 23);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Selling Price");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 370, 90, 20);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total Price");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 400, 90, 23);

        txtreno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrenoActionPerformed(evt);
            }
        });
        jPanel1.add(txtreno);
        txtreno.setBounds(140, 100, 170, 27);

        txtitemno.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtitemno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemnoActionPerformed(evt);
            }
        });
        txtitemno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtitemnoKeyReleased(evt);
            }
        });
        jPanel1.add(txtitemno);
        txtitemno.setBounds(140, 170, 170, 27);

        datereceive.setDateFormatString("yyyy- MM-dd");
        datereceive.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                datereceiveFocusGained(evt);
            }
        });
        jPanel1.add(datereceive);
        datereceive.setBounds(140, 130, 170, 30);

        dateexpire.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(dateexpire);
        dateexpire.setBounds(140, 260, 170, 30);

        txtitemname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtitemname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtitemnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtitemname);
        txtitemname.setBounds(140, 200, 170, 27);

        txtdescription.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txtdescription);
        txtdescription.setBounds(140, 230, 170, 27);

        txtquentity.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtquentity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquentityActionPerformed(evt);
            }
        });
        txtquentity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtquentityKeyTyped(evt);
            }
        });
        jPanel1.add(txtquentity);
        txtquentity.setBounds(140, 300, 170, 27);

        txtbuyprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtbuyprice.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtbuypriceComponentAdded(evt);
            }
        });
        txtbuyprice.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtbuypriceAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtbuyprice.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtbuypriceCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtbuypriceInputMethodTextChanged(evt);
            }
        });
        txtbuyprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuypriceActionPerformed(evt);
            }
        });
        txtbuyprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuypriceKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuypriceKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuypriceKeyTyped(evt);
            }
        });
        jPanel1.add(txtbuyprice);
        txtbuyprice.setBounds(140, 330, 170, 27);

        txtsellprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtsellprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsellpriceActionPerformed(evt);
            }
        });
        txtsellprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsellpriceKeyTyped(evt);
            }
        });
        jPanel1.add(txtsellprice);
        txtsellprice.setBounds(140, 360, 170, 27);

        txttotalprice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txttotalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalpriceActionPerformed(evt);
            }
        });
        txttotalprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttotalpriceKeyTyped(evt);
            }
        });
        jPanel1.add(txttotalprice);
        txttotalprice.setBounds(140, 390, 170, 30);

        jLabel18.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Search By");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(360, 30, 100, 26);

        cmbsearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbsearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Tittle", "receive_no", "item_number", "item_name" }));
        jPanel1.add(cmbsearch);
        cmbsearch.setBounds(480, 30, 180, 26);

        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search1.png"))); // NOI18N
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch);
        btnsearch.setBounds(850, 30, 40, 26);

        txtsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        txtsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtsearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtsearch);
        txtsearch.setBounds(670, 30, 180, 26);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background4.jpg"))); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel15);
        jLabel15.setBounds(330, 20, 580, 40);

        btnclear.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnclear.setText("Clear");
        btnclear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(660, 420, 90, 37);

        btnprint.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        btnprint.setText("Print");
        btnprint.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint);
        btnprint.setBounds(810, 420, 90, 37);

        btndelete.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel1.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete);
        btndelete.setBounds(490, 420, 99, 37);

        btnselect.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        btnselect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/select.png"))); // NOI18N
        btnselect.setText("Select");
        btnselect.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnselect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnselectActionPerformed(evt);
            }
        });
        jPanel1.add(btnselect);
        btnselect.setBounds(340, 420, 90, 37);

        jPanel2.setLayout(new java.awt.CardLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background6.jpg"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel2.add(jLabel19, "card2");

        jPanel3.setLayout(null);

        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit-validated-icon (1).png"))); // NOI18N
        btnupdate.setText("update");
        btnupdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnupdate);
        btnupdate.setBounds(10, 0, 130, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background6.jpg"))); // NOI18N
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel3.add(jLabel20);
        jLabel20.setBounds(0, 0, 150, 50);

        jPanel2.add(jPanel3, "card3");

        jPanel4.setLayout(null);

        btnsave.setFont(new java.awt.Font("Lucida Bright", 3, 16)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Button-Ok-icon.png"))); // NOI18N
        btnsave.setText("SAVE");
        btnsave.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnsave.setMaximumSize(new java.awt.Dimension(79, 27));
        btnsave.setMinimumSize(new java.awt.Dimension(79, 27));
        btnsave.setPreferredSize(new java.awt.Dimension(79, 27));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel4.add(btnsave);
        btnsave.setBounds(10, 0, 130, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background6.jpg"))); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel4.add(jLabel21);
        jLabel21.setBounds(0, 0, 150, 50);

        jPanel2.add(jPanel4, "card4");

        jPanel1.add(jPanel2);
        jPanel2.setBounds(170, 430, 150, 50);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableitemlist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableitemlist.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableitemlist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableitemlistMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableitemlist);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(342, 80, 560, 290);

        lblbarcode.setEditable(false);
        lblbarcode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(lblbarcode);
        lblbarcode.setBounds(40, 430, 130, 45);

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel16);
        jLabel16.setBounds(330, 70, 580, 310);

        jLabel17.setFont(new java.awt.Font("Lucida Bright", 3, 14)); // NOI18N
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(330, 390, 580, 90);

        jLabel14.setFont(new java.awt.Font("Sitka Text", 3, 14)); // NOI18N
        jLabel14.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel14);
        jLabel14.setBounds(30, 60, 290, 420);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background6.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(0, 0, 940, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttotalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalpriceActionPerformed

    private void txtsellpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsellpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsellpriceActionPerformed

    private void txtbuypriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuypriceActionPerformed
       
    }//GEN-LAST:event_txtbuypriceActionPerformed

    private void txtrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrenoActionPerformed

    private void txtitemnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemnoActionPerformed
      
    }//GEN-LAST:event_txtitemnoActionPerformed

    private void txtquentityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquentityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquentityActionPerformed

    private void txtitemnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtitemnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtitemnameActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        tablelord();
        autoId();
        panelord();
        clearField();
        txtsearch.setText("");
        btnprint.setEnabled(true);
        btndelete.setEnabled(false);
        btnselect.setEnabled(false);
       
        
        
    }//GEN-LAST:event_btnclearActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
   String tit=cmbsearch.getSelectedItem().toString();
   
       
    }//GEN-LAST:event_btnsearchActionPerformed

    private void receiveStocksearch()
    {
        String tit=cmbsearch.getSelectedItem().toString();
        
       try {
            if(tit=="receive_no")
            {
             
             parseSql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where receive_no Like'%"+txtsearch.getText()+"%' and mark='1'";
            pst=conn.prepareStatement(parseSql);
            rs=pst.executeQuery();
            tableitemlist.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }
            else if(tit=="item_number")
            {
             parseSql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where item_number LIKE'%"+txtsearch.getText()+"%' and mark='1'";
            pst=conn.prepareStatement(parseSql);
            rs=pst.executeQuery();
            tableitemlist.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }
            else if(tit=="item_name")
            {
             
              parseSql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where item_name Like'%"+txtsearch.getText()+"%' and mark='1'";
            pst=conn.prepareStatement(parseSql);
            rs=pst.executeQuery();
            tableitemlist.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "Please select tittle for Search");
            }
            
        } catch (Exception e) {
        } 
    }
    
    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsearchActionPerformed

    private void panelord()
    {
    jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
    
    }
    
    
     private void autoId()
    {
        try {
             String sql="SELECT receive_no FROM receivestock ORDER BY receive_no DESC LIMIT 1";
           // String q="SELECT returndate FROM borrowdetails where mid='"+ name +"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next())
           {
                String rnno=rs.getString("receive_no");
                int co=rnno.length();
               String txt= rnno.substring(0, 2);
               String num=rnno.substring(2, co);
               int n=Integer.parseInt(num);
               n++;
               String snum=Integer.toString(n);
               String ftxt=txt+snum;
               txtreno.setText(ftxt);
            
           }
           else
           {
               txtreno.setText("RN1000");
           }
           
                            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
       
    }
     
      private void tablelord()
    {
        try {
            String sql="SELECT receivestock.receive_no as 'RECEIVE NO', receivestock.receive_date as 'RECEIVE DATE', receivestock.item_number as 'ITEM NO', receivestock.item_name as 'ITEM NAME', receivestock.description as 'DESCRIPTION', receivestock.quentity as 'QUANTITY', receivestock.expire_date as 'EXPRIER DATE', receivestock.buying_price as 'BUYING PRICE', receivestock.selling_price as 'SELLING PRICE', receivestock.total_price as 'TOTAL PRICE' FROM receivestock where mark='"+1+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tableitemlist.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
       theader();
    }
      private void clearField()
      {
         // txtreno.setText("");
         ((JTextField)datereceive.getDateEditor().getUiComponent()).setText("");
         txtitemno.setText("");
         txtitemname.setText("");
         txtdescription.setText("");
         txtquentity.setText("");
         ((JTextField)dateexpire.getDateEditor().getUiComponent()).setText("");
         txtbuyprice.setText("");
         txtsellprice.setText("");
         txttotalprice.setText("");
         txtsearch.setText("");
      }
    
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       String receno=txtreno.getText();
       String redate=((JTextField)datereceive.getDateEditor().getUiComponent()).getText();
       String itemno=txtitemno.getText();
       String itemna=txtitemname.getText();
       String descri=txtdescription.getText();
       String quentity=txtquentity.getText();
       String exdate=((JTextField)dateexpire.getDateEditor().getUiComponent()).getText();
       String buyprice=txtbuyprice.getText();
       String selprice=txtsellprice.getText();
       String totprice=txttotalprice.getText();
       
        try {
                String q= "INSERT INTO `receivestock`(`receive_no`, `receive_date`, `item_number`, `item_name`, `description`, `quentity`, `expire_date`, `buying_price`, `selling_price`, `total_price`,`mark`) VALUES ('"+receno+"','"+redate+"' ,'"+itemno+"' ,'"+itemna+"' ,'"+descri+"' ,'"+quentity+"' ,'"+exdate+"' ,'"+buyprice+"' ,'"+selprice+"' ,'"+totprice+"','"+1+"')";
                 pst=conn.prepareStatement(q);
                pst.execute(); 
                JOptionPane.showMessageDialog(rootPane,"save success");
                
                    } 
                catch (Exception e) 
                {
       
                 JOptionPane.showMessageDialog(rootPane,e);                    
                }  
             tablelord();   
             autoId(); 
             clearField();
             btnsave.setEnabled(false);
             seDeAddDisable();
             btnprint.setEnabled(true);
            lblbarcode.setText("");
               
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtbuypriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuypriceKeyReleased
       
        double pri=Integer.parseInt(txtbuyprice.getText());
        double que=Integer.parseInt(txtquentity.getText());
        double tpri=pri*que;
        txttotalprice.setText(String.valueOf(tpri));      
    }//GEN-LAST:event_txtbuypriceKeyReleased

    private void txtbuypriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuypriceKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)&& !evt.isAltDown())
        {
        evt.consume();
        }
        btnsave.setEnabled(true);
    }//GEN-LAST:event_txtbuypriceKeyTyped

    private void txtbuypriceInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbuypriceInputMethodTextChanged
        
    }//GEN-LAST:event_txtbuypriceInputMethodTextChanged

    private void txtbuypriceAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtbuypriceAncestorAdded
        
    }//GEN-LAST:event_txtbuypriceAncestorAdded

    private void txtbuypriceComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtbuypriceComponentAdded
        
    }//GEN-LAST:event_txtbuypriceComponentAdded

    private void txtbuypriceCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtbuypriceCaretPositionChanged
        
    }//GEN-LAST:event_txtbuypriceCaretPositionChanged

    private void txtbuypriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuypriceKeyPressed
        
    }//GEN-LAST:event_txtbuypriceKeyPressed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
  
   int prcount=tableitemlist.getRowCount();
    if(prcount>0)
    {
        DefaultTableModel tableModel=(DefaultTableModel)tableitemlist.getModel();
        try {
           
           tableitemlist.print();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane, "Not Details to print");
    }    
    }//GEN-LAST:event_btnprintActionPerformed

    private void allReceive()
    {
    }
    
    private void filterReceive()
    {
    
    }
    
    
    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        
       delete();
       seDeAddDisable();
       btnprint.setEnabled(true);
       clearField();
        
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnselectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnselectActionPerformed
       
        try {
            String sq="SELECT `receive_no`, `receive_date`, `item_number`, `item_name`, `description`, `quentity`, `expire_date`, `buying_price`, `selling_price`, `total_price` FROM `receivestock` WHERE receive_no='"+txtsearch.getText()+"'";
           
            pst=conn.prepareStatement(sq);
            rs=pst.executeQuery();
            while(rs.next()){
                txtreno.setText(rs.getString("receive_no"));
                ((JTextField)datereceive.getDateEditor().getUiComponent()).setText(rs.getString("receive_date"));
                txtitemno.setText(rs.getString("item_number"));
                txtitemname.setText(rs.getString("item_name"));
                txtdescription.setText(rs.getString("description"));
                txtquentity.setText(rs.getString("quentity"));
                ((JTextField)dateexpire.getDateEditor().getUiComponent()).setText(rs.getString("expire_date"));
                txtbuyprice.setText(rs.getString("buying_price"));
                txtsellprice.setText(rs.getString("selling_price"));
                txttotalprice.setText(rs.getString("total_price"));
                
            }
        } catch (Exception e) {
        }
        
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel3);
        jPanel2.repaint();
        jPanel2.revalidate();
        
        btnupdate.setEnabled(true);
        seDeAddDisable();
        barcode();
        
    }//GEN-LAST:event_btnselectActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
       
        datalord();
        jPanel2.removeAll();
        jPanel2.repaint();
        jPanel2.revalidate();
        
        jPanel2.add(jPanel4);
        jPanel2.repaint();
        jPanel2.revalidate();
        
        clearField();
         autoId();
        seDeAddDisable();
        btnprint.setEnabled(true);
        lblbarcode.setText("");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void seDeAddDisable()
    {
    
         btndelete.setEnabled(false);
         btnselect.setEnabled(false);
      
    }
    
    private void txtquentityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquentityKeyTyped
        
        char c=evt.getKeyChar();
        if(Character.isLetter(c)&& !evt.isAltDown())
        {
        evt.consume();
        }
        
    }//GEN-LAST:event_txtquentityKeyTyped

    private void txtsellpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsellpriceKeyTyped
       char c=evt.getKeyChar();
        if(Character.isLetter(c)&& !evt.isAltDown())
        {
        evt.consume();
        }
    }//GEN-LAST:event_txtsellpriceKeyTyped

    private void txttotalpriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalpriceKeyTyped
        char c=evt.getKeyChar();
        if(Character.isLetter(c)&& !evt.isAltDown())
        {
        evt.consume();
        }
    }//GEN-LAST:event_txttotalpriceKeyTyped

    private void delete()
    {
         int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to delete");
        if(x==0)
        {
        try {
                String sql="DELETE FROM receivestock where receive_no='"+ txtsearch.getText() +"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                
                tablelord();
            } catch (Exception e) {
            }
        }
    
    }
    private void markitem()
    {
      try {
              String squpdate = "UPDATE receivestock SET mark=mark -'"+1+"' WHERE receive_no='"+txtsearch.getText()+"'";
              pst=conn.prepareStatement(squpdate);
                pst.execute();  
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);              
            }  
    }
    
    
    private void tableitemlistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableitemlistMouseClicked
      
        DefaultTableModel tmodel=(DefaultTableModel)tableitemlist.getModel();
        int selectrowindex=tableitemlist.getSelectedRow();
        txtsearch.setText(tmodel.getValueAt(selectrowindex, 0).toString());
        
        
        btndelete.setEnabled(true);
        btnselect.setEnabled(true);
        btnprint.setEnabled(false);
    }//GEN-LAST:event_tableitemlistMouseClicked

    private void datereceiveFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_datereceiveFocusGained
      
       
    }//GEN-LAST:event_datereceiveFocusGained

    private void txtsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsearchKeyReleased
      receiveStocksearch();
    }//GEN-LAST:event_txtsearchKeyReleased

    private void txtitemnoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemnoKeyReleased
       barcode();
    }//GEN-LAST:event_txtitemnoKeyReleased
private void barcode()
{

 
}


private void datalord()
{

    String receno=txtreno.getText();
       String redate=((JTextField)datereceive.getDateEditor().getUiComponent()).getText();
       String itemno=txtitemno.getText();
       String itemna=txtitemname.getText();
       String descri=txtdescription.getText();
       String quentity=txtquentity.getText();
       String exdate=((JTextField)dateexpire.getDateEditor().getUiComponent()).getText();
       String buyprice=txtbuyprice.getText();
       String selprice=txtsellprice.getText();
       String totprice=txttotalprice.getText();
        
         int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to update");
        if(x==0)
        {
        try {
              String squpdate = "UPDATE `receivestock` SET `receive_no`='"+receno+"',`receive_date`='"+redate+"',`item_number`='"+itemno+"',`item_name`='"+itemna+"',`description`='"+descri+"',`quentity`='"+quentity+"',`expire_date`='"+exdate+"',`buying_price`='"+buyprice+"',`selling_price`='"+selprice+"',`total_price`='"+totprice+"' WHERE receive_no='"+txtsearch.getText()+"'";
              pst=conn.prepareStatement(squpdate);
                pst.execute();  
                tablelord();
            } catch (Exception e) {
            }
        }

}
    
private void loDisable()
{
    btnsave.setEnabled(false);
    btnupdate.setEnabled(false);
    btnselect.setEnabled(false);
    btndelete.setEnabled(false);
   // btnclear.setEnabled(false);
  
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnselect;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cmbsearch;
    private com.toedter.calendar.JDateChooser dateexpire;
    private com.toedter.calendar.JDateChooser datereceive;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lblbarcode;
    private javax.swing.JTable tableitemlist;
    private javax.swing.JTextField txtbuyprice;
    private javax.swing.JTextField txtdescription;
    private javax.swing.JTextField txtitemname;
    private javax.swing.JTextField txtitemno;
    private javax.swing.JTextField txtquentity;
    private javax.swing.JTextField txtreno;
    private javax.swing.JTextField txtsearch;
    private javax.swing.JTextField txtsellprice;
    private javax.swing.JTextField txttotalprice;
    // End of variables declaration//GEN-END:variables
}
