/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;
import java.lang.*;
//import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.awt.Color;
import java.awt.Font;
import java.awt.List;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;  




public class Report extends javax.swing.JInternalFrame {


    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    PreparedStatement pst1=null;
    ResultSet rs1=null;
    String sqr1;
    Connection conn1;
    Object[] column={"Business_Date","Total_Sale","Transaction","Net_Income"};
    DefaultTableModel dTM=new DefaultTableModel();
    Object[] row=new Object[4];
    private String reportSql;
    private int selectrow;
    Double saleReturn;
    Double reCost;
    
    
    public Report() {
        initComponents();
        conn=DBConnect.connect();
        conn1=DBConnect.connect();
        saleLord();
        lordBtnDissable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsale = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblprintDetails = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fromDate = new com.toedter.calendar.JDateChooser();
        toDate = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtsalesum = new javax.swing.JTextField();
        txtincome = new javax.swing.JTextField();
        txttransaction = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btndelet = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(950, 530));

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sale Report");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 10, 180, 31);

        tblsale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblsale);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(70, 90, 350, 180);

        tblprintDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblprintDetails.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblprintDetails.setAutoscrolls(false);
        tblprintDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblprintDetailsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblprintDetails);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(440, 90, 430, 180);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sales Value");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 60, 130, 20);

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Daily Sales");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(450, 60, 120, 20);

        jLabel11.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("From");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 320, 50, 21);

        fromDate.setDateFormatString("yyyy-MM-dd");
        fromDate.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                fromDatePropertyChange(evt);
            }
        });
        jPanel1.add(fromDate);
        fromDate.setBounds(150, 320, 180, 30);

        toDate.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(toDate);
        toDate.setBounds(370, 320, 180, 30);

        jLabel12.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("To");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(340, 320, 19, 21);

        jLabel10.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Select Date");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 300, 110, 20);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(553, 320, 110, 30);

        jLabel9.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(70, 290, 600, 70);

        jLabel14.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Total Sales");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(80, 390, 100, 21);

        jLabel15.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Net Incomes");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(80, 420, 97, 21);

        jLabel16.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Transactions");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(370, 390, 102, 21);

        txtsalesum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtsalesum.setText("0.0");
        txtsalesum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalesumActionPerformed(evt);
            }
        });
        jPanel1.add(txtsalesum);
        txtsalesum.setBounds(200, 380, 150, 30);

        txtincome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtincome.setText("0.0");
        txtincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtincomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtincome);
        txtincome.setBounds(200, 420, 150, 30);

        txttransaction.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txttransaction.setText("0");
        jPanel1.add(txttransaction);
        txttransaction.setBounds(480, 380, 160, 30);

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave);
        btnsave.setBounds(390, 420, 110, 30);

        btnclear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/clear.png"))); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        jPanel1.add(btnclear);
        btnclear.setBounds(530, 420, 110, 33);

        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 370, 600, 90);

        btndelet.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btndelet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel1.png"))); // NOI18N
        btndelet.setText("Delete");
        btndelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletActionPerformed(evt);
            }
        });
        jPanel1.add(btndelet);
        btndelet.setBounds(690, 360, 160, 40);

        btnprint.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print32.png"))); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint);
        btnprint.setBounds(690, 410, 160, 40);

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel17);
        jLabel17.setBounds(680, 290, 180, 170);

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 280, 810, 190);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 80, 880, 400);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background4.jpg"))); // NOI18N
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 50, 880, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background4.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 0, 880, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background6.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 940, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromDatePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_fromDatePropertyChange
       
    }//GEN-LAST:event_fromDatePropertyChange

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       saleFilter();
       int stv=Integer.parseInt(txttransaction.getText());
       if(stv>0)
       {
       btnsave.setEnabled(true);
       }    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
       fClear();
       btnsave.setEnabled(false);
    }//GEN-LAST:event_btnclearActionPerformed
    
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
       
        dTM.setColumnIdentifiers(column);
        tblprintDetails.setModel(dTM);
        theader();
        String saleFDate=((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
        String saleTDate=((JTextField)toDate.getDateEditor().getUiComponent()).getText();
        try {
              row[0]=saleFDate+"   "+saleTDate;
              row[1]=txtsalesum.getText();
              row[2]=txttransaction.getText();
              row[3]=txtincome.getText();
              dTM.addRow(row);
        } catch (Exception e) {
        }
         fClear();
         btnprint.setEnabled(true);
         btnsave.setEnabled(false);       
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtsalesumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalesumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalesumActionPerformed

    private void txtincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtincomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtincomeActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
   int prcount=tblprintDetails.getRowCount();
    if(prcount>0)
    {
        DefaultTableModel tableModel=(DefaultTableModel)tblprintDetails.getModel();
        try {
            tblprintDetails.print();
        } catch (Exception e) {
        }
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane, "Not Details to print");
    }    
    }//GEN-LAST:event_btnprintActionPerformed

    private void btndeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletActionPerformed
        dTM.removeRow(tblprintDetails.getSelectedRow());
        btndelet.setEnabled(false);
    }//GEN-LAST:event_btndeletActionPerformed

    private void tblprintDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblprintDetailsMouseClicked
        btndelet.setEnabled(true);
    }//GEN-LAST:event_tblprintDetailsMouseClicked
    private void lordBtnDissable()
    {
        btnsave.setEnabled(false);
        btndelet.setEnabled(false);
        btnprint.setEnabled(false);
    }
    
 

    
    private void saleFilter()
    {
        String saleFDate=((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
        String saleTDate=((JTextField)toDate.getDateEditor().getUiComponent()).getText();
        if(saleFDate.length()>0 && saleTDate.isEmpty())
        {
         try {
            reportSql="SELECT `sin` as 'Invoice No', `total` as 'Sale Value', `profit` as 'Profit', `date` as 'Date' FROM `payment` where date='"+saleFDate+"'";
            pst1=conn1.prepareStatement(reportSql);
            rs1=pst1.executeQuery();
            tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
            int tr=tblsale.getRowCount();
            txttransaction.setText(Integer.toString(tr));
            if(tr>0)
            {
            calCost();
            }
            else
            {
            JOptionPane.showMessageDialog(rootPane, "Empty Record");
            }
         } 
            catch (Exception e) {
                 JOptionPane.showMessageDialog(rootPane, "frist date");
                                }
        }
     
        else if(saleFDate.length()>0 && saleTDate.length()>0)
        {
        try {
            reportSql="SELECT `sin` as 'Invoice No', `total` as 'Sale Value', `profit` as 'Profit', `date` as 'Date' FROM `payment` where date between'"+saleFDate+"' and '"+saleTDate+"' ";
            pst1=conn1.prepareStatement(reportSql);
            rs1=pst1.executeQuery();
            tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs1));
            
            int tr=tblsale.getRowCount();
           txttransaction.setText(Integer.toString(tr));
                  if(tr>0)
                 {
                calCost2();
                 }
                 else
                 {
                 JOptionPane.showMessageDialog(rootPane, "Empty Record");
                 } 
         } catch (Exception e) {
              JOptionPane.showMessageDialog(rootPane, e);
                                }
           }
        else
        {
          JOptionPane.showMessageDialog(rootPane, "Select date to filter data");  
        }    
    }
    
    
    
    private  void  calCost()
    {
     String saleFDate=((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
        try {
            String sq="SELECT sum(total),sum(profit) from payment where date='"+saleFDate+"'";
            pst=conn.prepareStatement(sq);
            rs=pst.executeQuery();
           while(rs.next())
           {
               
            String sValue=rs.getString("sum(total)");
            String profit=rs.getString("sum(profit)");
           
            txtsalesum.setText(sValue);
            txtincome.setText(profit);
            }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
    
    }
    
     private  void  calCost2()
    {
     String saleFDate=((JTextField)fromDate.getDateEditor().getUiComponent()).getText();
     String saleTDate=((JTextField)toDate.getDateEditor().getUiComponent()).getText();
        try {
            String sq="SELECT sum(total),sum(profit) from payment where date between'"+saleFDate+"' and '"+saleTDate+"'";
            pst=conn.prepareStatement(sq);
            rs=pst.executeQuery();
           while(rs.next())
           {
            String sValue=rs.getString("sum(total)");
            String profit=rs.getString("sum(profit)");
            
            txtsalesum.setText(sValue);
            txtincome.setText(profit);  
            }
            } catch (Exception e) {
                 JOptionPane.showMessageDialog(rootPane, e);
            }    
    }
    
    
    private void fClear()
    {
        ((JTextField)fromDate.getDateEditor().getUiComponent()).setText("");
        ((JTextField)toDate.getDateEditor().getUiComponent()).setText("");
        txtsalesum.setText("0.0");
        txttransaction.setText("0");
        txtincome.setText("0.0");
        saleLord();
    }
            
     private void  theader()
    {
    JTableHeader thead = tblprintDetails.getTableHeader();
       thead.setForeground(Color.BLUE);
       thead.setFont(new Font("Tahome", Font.BOLD, 14));
       TableColumn col1=tblprintDetails.getColumnModel().getColumn(0);
       col1.setPreferredWidth(150);
       TableColumn col2=tblprintDetails.getColumnModel().getColumn(1);
       col2.setPreferredWidth(110);
       TableColumn col3=tblprintDetails.getColumnModel().getColumn(2);
       col3.setPreferredWidth(130);
       TableColumn col4=tblprintDetails.getColumnModel().getColumn(3);
       col4.setPreferredWidth(130);
    }
    
   private void saleLord()
    {
    try {
        String sql="SELECT `sin` as 'Invoice No', `total` as 'Sale Value', `profit` as 'Profit', `date` as 'Date' FROM `payment`";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
    } catch (Exception e) {
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btndelet;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnsave;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblprintDetails;
    private javax.swing.JTable tblsale;
    private com.toedter.calendar.JDateChooser toDate;
    private javax.swing.JTextField txtincome;
    private javax.swing.JTextField txtsalesum;
    private javax.swing.JTextField txttransaction;
    // End of variables declaration//GEN-END:variables
}
