/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurant;
import java.lang.*;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.MessageFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;




public class Stock extends javax.swing.JInternalFrame {

   
    
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    String sqr;
    
    public Stock() {
        initComponents();
        conn=DBConnect.connect();
        tablelord();
        btndelete.setEnabled(false);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtitemname = new javax.swing.JTextField();
        lblname = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblstock = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnfind = new javax.swing.JButton();
        dateex = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(950, 530));

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stocks");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 50, 120, 26);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print32.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(770, 430, 110, 40);

        txtitemname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtitemname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtitemnameKeyReleased(evt);
            }
        });
        jPanel1.add(txtitemname);
        txtitemname.setBounds(710, 50, 180, 30);

        lblname.setFont(new java.awt.Font("Sitka Text", 3, 20)); // NOI18N
        lblname.setForeground(new java.awt.Color(255, 255, 255));
        lblname.setText("ENTER NAME");
        jPanel1.add(lblname);
        lblname.setBounds(560, 50, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background4.jpg"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 40, 860, 50);

        tblstock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblstock.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblstock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstockMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblstock);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 100, 840, 250);

        jLabel6.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Expiry dates");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 380, 130, 20);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 410, 70, 21);

        jButton4.setBackground(new java.awt.Color(102, 255, 102));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/reset.png"))); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(650, 430, 110, 40);

        btndelete.setBackground(new java.awt.Color(255, 51, 51));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cancel1.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete);
        btndelete.setBounds(530, 430, 110, 40);

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(510, 420, 390, 60);

        btnfind.setBackground(new java.awt.Color(102, 255, 102));
        btnfind.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnfind.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        btnfind.setText("Find");
        btnfind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfindActionPerformed(evt);
            }
        });
        jPanel1.add(btnfind);
        btnfind.setBounds(250, 440, 100, 30);

        dateex.setDateFormatString("yyyy-MM-dd");
        dateex.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                dateexComponentAdded(evt);
            }
        });
        dateex.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                dateexHierarchyChanged(evt);
            }
        });
        dateex.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dateexFocusGained(evt);
            }
        });
        dateex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateexMouseClicked(evt);
            }
        });
        dateex.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                dateexInputMethodTextChanged(evt);
            }
        });
        dateex.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateexPropertyChange(evt);
            }
        });
        dateex.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dateexKeyTyped(evt);
            }
        });
        jPanel1.add(dateex);
        dateex.setBounds(140, 400, 210, 30);

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 370, 320, 110);

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 90, 860, 270);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/background6.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 950, 530);
        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(550, 110, 100, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void  taheader()
    {
        JTableHeader thead = tblstock.getTableHeader();
        thead.setForeground(Color.BLUE);    
        thead.setFont(new Font("Tahome", Font.BOLD, 14));       
        TableColumn col1=tblstock.getColumnModel().getColumn(0);
        col1.setPreferredWidth(95);
        TableColumn col2=tblstock.getColumnModel().getColumn(1);
        col2.setPreferredWidth(100);
        TableColumn col3=tblstock.getColumnModel().getColumn(2);
        col3.setPreferredWidth(85);
        TableColumn col4=tblstock.getColumnModel().getColumn(3);
        col4.setPreferredWidth(104);
        TableColumn col5=tblstock.getColumnModel().getColumn(4);
        col5.setPreferredWidth(100);
        TableColumn col6=tblstock.getColumnModel().getColumn(5);
        col6.setPreferredWidth(100);
        TableColumn col7=tblstock.getColumnModel().getColumn(6);
        col7.setPreferredWidth(110);
        TableColumn col8=tblstock.getColumnModel().getColumn(7);
        col8.setPreferredWidth(115);
         TableColumn col9=tblstock.getColumnModel().getColumn(8);
        col9.setPreferredWidth(115);
         TableColumn col10=tblstock.getColumnModel().getColumn(9);
        col10.setPreferredWidth(115);
    }
    
     private void tablelord()
    {
        try {
            String sql="SELECT `receive_no` as 'Receive No', `receive_date` as 'Receive Date', `item_number` as 'Item No', `item_name` as 'Item Name', `description` as 'Description', `quentity` as 'Quentity', `expire_date` as 'Expier Date', `buying_price` as 'Unit Cost', `selling_price` as 'Sell Price', `total_price` as 'Total Price' FROM `receivestock`";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));            
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
        taheader();
    }
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

           int prcount=tblstock.getRowCount();
    if(prcount>0)
    {
        DefaultTableModel tableModel=(DefaultTableModel)tblstock.getModel();
        try {
           
            tblstock.print();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    else
    {
        JOptionPane.showMessageDialog(rootPane, "Not Details to print");
    }    

    }//GEN-LAST:event_jButton1ActionPerformed
   

    
    private void fullStock()
    {
    
    }
   
        
    private void btnfindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfindActionPerformed
    
        String exdate=((JTextField)dateex.getDateEditor().getUiComponent()).getText();
        if(exdate.length()>0)
        {
        txtitemname.setText("");
        try {
            String sql="SELECT `receive_no` as 'Receive No', `receive_date` as 'Receive Date', `item_number` as 'Item No', `item_name` as 'Item Name', `description` as 'Description', `quentity` as 'Quentity', `expire_date` as 'Expier Date', `buying_price` as 'Unit Cost', `selling_price` as 'Sell Price', `total_price` as 'Total Price' FROM `receivestock` where receivestock.expire_date <='"+exdate+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        taheader();
        }
        else
        {
        JOptionPane.showMessageDialog(rootPane, "Select Date To Find Details");
        }
    }//GEN-LAST:event_btnfindActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       tablelord();
       ((JTextField)dateex.getDateEditor().getUiComponent()).setText("");
       txtitemname.setText("");            
       btndelete.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void dateexComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_dateexComponentAdded
     
    }//GEN-LAST:event_dateexComponentAdded

    private void dateexInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_dateexInputMethodTextChanged
        
    }//GEN-LAST:event_dateexInputMethodTextChanged

    private void dateexPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateexPropertyChange
       
    }//GEN-LAST:event_dateexPropertyChange

    private void dateexHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_dateexHierarchyChanged
        
    }//GEN-LAST:event_dateexHierarchyChanged

    private void dateexKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateexKeyTyped
       
    }//GEN-LAST:event_dateexKeyTyped

    private void dateexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateexMouseClicked
        
    }//GEN-LAST:event_dateexMouseClicked

    private void dateexFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_dateexFocusGained
      
    }//GEN-LAST:event_dateexFocusGained

    private void txtitemnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtitemnameKeyReleased
        ((JTextField)dateex.getDateEditor().getUiComponent()).setText("");
        String itemname=txtitemname.getText();
        try {
            String sql="SELECT `receive_no` as 'Receive No', `receive_date` as 'Receive Date', `item_number` as 'Item No', `item_name` as 'Item Name', `description` as 'Description', `quentity` as 'Quentity', `expire_date` as 'Expier Date', `buying_price` as 'Unit Cost', `selling_price` as 'Sell Price', `total_price` as 'Total Price' FROM `receivestock` where receivestock.item_name LIKE'%"+ itemname +"%'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblstock.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        taheader();
    }//GEN-LAST:event_txtitemnameKeyReleased

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed

        DefaultTableModel tmodel=(DefaultTableModel)tblstock.getModel();
        int selectrowindex=tblstock.getSelectedRow();
        String reitm=(tmodel.getValueAt(selectrowindex, 0).toString());
        int x=JOptionPane.showConfirmDialog(rootPane, "Do you realy want to delete");
        if(x==0)
        {
        try {
                String sql="DELETE FROM stock where receive_no='"+ reitm +"'";
                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(rootPane, "successfully deleted");
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,e);
            }
       
        }
        tablelord();
        btndelete.setEnabled(false);
    }//GEN-LAST:event_btndeleteActionPerformed

    private void tblstockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstockMouseClicked
         btndelete.setEnabled(true);
    }//GEN-LAST:event_tblstockMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnfind;
    private com.toedter.calendar.JDateChooser dateex;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblname;
    private javax.swing.JTable tblstock;
    private javax.swing.JTextField txtitemname;
    // End of variables declaration//GEN-END:variables
}
